#!/usr/bin/env python
# Class autogenerated from /home/sam/Downloads/aldebaran_sw/nao/naoqi-sdk-2.1.4.13-linux64/include/alproxies/alexpressivelisteningproxy.h
# by Sammy Pfeiffer's <Sammy.Pfeiffer at student.uts.edu.au> generator
# You need an ALBroker running

from naoqi import ALProxy



class ALExpressiveListening(object):
    def __init__(self):
        self.proxy = None

    def force_connect(self):
        self.proxy = ALProxy("ALExpressiveListening")

    def getParameter(self, parameter):
        """Get the specified parameter.

        :param str parameter: Name of the parameter.  "MinTimeBeforeFirstNod" : Minimum time (in seconds) before first nod.  "MaxTimeBeforeFirstNod" : Maximum time (in seconds) before first nod.  "MinTimeBetweenNods" : Minimum time (in seconds) between two nods.  "MaxTimeBetweenNods" : Maximum time (in seconds) between two nods.  "SpeedNods" : Speed of head moves when nodding  "SpeedServoing" : Speed of head moves when servoing.  "FrameRateTracking3D" : 3D tracking's framerate.  "FrameRateTracking2D" : 2D tracking's framerate.  "NobodyFoundTimeOut" : timeout to send peopleLeft event when no blob isfound  "AmplitudeNod" : amplitude of the nod (angle made by Up and Down positions), in degree  "AmplitudeYawTracking" : max absolute value for head yaw in tracking, in degrees
        :returns AL::ALValue: ALValue format for required parameter
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.getParameter(parameter)

    def isListening(self):
        """Get the status (started or not) of the module.

        :returns bool: 
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.isListening()

    def isNoddingEnabled(self):
        """Get status enabled/disabled for Nodding

        :returns bool: Boolean value for status enabled/disabled
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.isNoddingEnabled()

    def isPaused(self):
        """Get the pause status of the module.

        :returns bool: 
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.isPaused()

    def isTracking3DEnabled(self):
        """Get status enabled/disabled for tracking.

        :returns bool: Boolean value for status enabled/disabled
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.isTracking3DEnabled()

    def pauseListening(self):
        """Pause Expressive Listening.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.pauseListening()

    def ping(self):
        """Just a ping. Always returns true

        :returns bool: returns true
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.ping()

    def resumeListening(self):
        """Resume Expressive Listening.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.resumeListening()

    def setNoddingEnabled(self, enable):
        """Enable/Disable nodding.

        :param bool enable: Boolean value: true to enable, false to disable.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.setNoddingEnabled(enable)

    def setParameter(self, parameter, value):
        """Set the specified parameter.

        :param str parameter: Name of the parameter.  "MinTimeBeforeFirstNod" : Minimum time (in seconds) before first nod.  "MaxTimeBeforeFirstNod" : Maximum time (in seconds) before first nod.  "MinTimeBetweenNods" : Minimum time (in seconds) between two nods.  "MaxTimeBetweenNods" : Maximum time (in seconds) between two nods.  "SpeedNods" : Speed of head moves when nodding  "SpeedServoing" : Speed of head moves when servoing.  "FrameRateTracking3D" : 3D tracking's framerate.  "FrameRateTracking2D" : 2D tracking's framerate.  "NobodyFoundTimeOut" : timeout to send peopleLeft event when no blob isfound  "AmplitudeNod" : amplitude of the nod (angle made by Up and Down positions), in degree  "AmplitudeYawTracking" : max absolute value for head yaw in tracking, in degrees
        :param AL::ALValue value: "MinTimeBeforeFirstNod" : Float in range [0;5]  "MaxTimeBeforeFirstNod" : Float in range [0;5]  "MinTimeBetweenNods" : Float in range [0;5]  "MaxTimeBetweenNods" : Float in range [0;5]  "SpeedNods" : Float in range [0;1]  "SpeedServoing" : Float in range [0;1]  "FrameRateTracking3D" : Float in range [0.1;30]  "FrameRateTracking2D" : Float in range [0.1;30]  "NobodyFoundTimeOut" : Float > 0  "AmplitudeNod" : Float in range [0;45]  "AmplitudeYawTracking" : Float in range [10;120]
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.setParameter(parameter, value)

    def setTracking3DEnabled(self, enable):
        """Enable/Disable tracking.

        :param bool enable: Boolean value: true to enable, false to disable.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.setTracking3DEnabled(enable)

    def startListening(self):
        """Start Expressive Listening.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.startListening()

    def stopListening(self):
        """Stop Expressive Listening.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.stopListening()

    def version(self):
        """Returns the version of the module.

        :returns str: A string containing the version of the module.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALExpressiveListening")
        return self.proxy.version()
