#!/usr/bin/env python
# Class autogenerated from /home/sam/Downloads/softbank/naoqi-sdk-2.5.5.5-linux64/include/alproxies/alloggerproxy.h
# by Sammy Pfeiffer's <Sammy.Pfeiffer at student.uts.edu.au> generator
# You need an ALBroker running

from naoqi import ALProxy



class ALLogger(object):
    def __init__(self):
        self.proxy = None

    def force_connect(self):
        self.proxy = ALProxy("ALLogger")

    def debug(self, moduleName, message):
        """DEPRECATED. Use qiLogDebug instead.  Log a debug message.

        :param str moduleName: Name of the module.
        :param str message: Log Message.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.debug(moduleName, message)

    def error(self, moduleName, message):
        """DEPRECATED. Use qiLogError instead.  Log an error.

        :param str moduleName: Name of the module.
        :param str message: Log Message.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.error(moduleName, message)

    def fatal(self, moduleName, message):
        """DEPRECATED. Use qiLogFatal instead.  Log a fatal error.

        :param str moduleName: Name of the module.
        :param str message: Log Message.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.fatal(moduleName, message)

    def info(self, moduleName, message):
        """DEPRECATED. Use qiLogInfo instead.  Log a info message.

        :param str moduleName: Name of the module.
        :param str message: Log Message.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.info(moduleName, message)

    def logInFile(self, fileName):
        """DEPRECATED. Create your own log handler with qilog and add it with qi::log::addHandler. See libqi documentation for more details.  Allows the logger to store logs in a file. Warning: this is not recomended on Nao.

        :param str fileName: The fileName to use. Relative to the user naoqi folder.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.logInFile(fileName)

    def logInForwarder(self, inputAddress):
        """DEPRECATED. Should not be used. Publish logs to a Log Forwarder. Pass an empty string in order to use the default value:  "tcp://localhost:50998"

        :param str inputAddress: Desired input ZMQ address of the Log Forwarder.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.logInForwarder(inputAddress)

    def ping(self):
        """Just a ping. Always returns true

        :returns bool: returns true
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.ping()

    def removeHandler(self, arg1):
        """Do not use since we cannot add any handler with the API.

        :param str arg1: arg
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.removeHandler(arg1)

    def setVerbosity(self, arg1):
        """

        :param str arg1: arg
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.setVerbosity(arg1)

    def verbosity(self):
        """Get verbosity level of qi logs.

        :returns int: Verbosity of naoqi logs.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.verbosity()

    def version(self):
        """Returns the version of the module.

        :returns str: A string containing the version of the module.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.version()

    def warn(self, moduleName, message):
        """DEPRECATED: use qiLogWarning instead. Log a warning.

        :param str moduleName: Name of the module.
        :param str message: Log Message.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.warn(moduleName, message)
