#!/usr/bin/env python
# Class autogenerated from /home/sam/Downloads/aldebaran_sw/nao/naoqi-sdk-2.1.4.13-linux64/include/alproxies/alloggerproxy.h
# by Sammy Pfeiffer's <Sammy.Pfeiffer at student.uts.edu.au> generator
# You need an ALBroker running

from naoqi import ALProxy



class ALLogger(object):
    def __init__(self):
        self.proxy = None

    def force_connect(self):
        self.proxy = ALProxy("ALLogger")

    def debug(self, moduleName, message):
        """DEPRECATED. Use qiLogDebug instead.   Log a debug message.

        :param str moduleName: Name of the module.
        :param str message: Log Message.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.debug(moduleName, message)

    def error(self, moduleName, message):
        """DEPRECATED. Use qiLogError instead.   Log an error.

        :param str moduleName: Name of the module.
        :param str message: Log Message.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.error(moduleName, message)

    def fatal(self, moduleName, message):
        """DEPRECATED. Use qiLogFatal instead.   Log a fatal error.

        :param str moduleName: Name of the module.
        :param str message: Log Message.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.fatal(moduleName, message)

    def info(self, moduleName, message):
        """DEPRECATED. Use qiLogInfo instead.   Log a info message.

        :param str moduleName: Name of the module.
        :param str message: Log Message.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.info(moduleName, message)

    def logInFile(self, arg1):
        """Removed: not implemented anymore.

        :param str arg1: arg
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.logInFile(arg1)

    def logInForwarder(self, arg1):
        """Removed: not implemented anymore.

        :param str arg1: arg
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.logInForwarder(arg1)

    def ping(self):
        """Just a ping. Always returns true

        :returns bool: returns true
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.ping()

    def removeHandler(self, arg1):
        """Removed: not implemented anymore.

        :param str arg1: arg
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.removeHandler(arg1)

    def setVerbosity(self, arg1):
        """Removed: not implemented anymore.

        :param str arg1: arg
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.setVerbosity(arg1)

    def verbosity(self):
        """Removed: not implemented anymore.

        :returns int: 
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.verbosity()

    def version(self):
        """Returns the version of the module.

        :returns str: A string containing the version of the module.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.version()

    def warn(self, moduleName, message):
        """DEPRECATED: use qiLogWarning instead. Log a warning.

        :param str moduleName: Name of the module.
        :param str message: Log Message.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALLogger")
        return self.proxy.warn(moduleName, message)
