#!/usr/bin/env python
# Class autogenerated from /home/sam/Downloads/aldebaran_sw/nao/naoqi-sdk-2.1.4.13-linux64/include/alproxies/almecaloggerproxy.h
# by Sammy Pfeiffer's <Sammy.Pfeiffer at student.uts.edu.au> generator
# You need an ALBroker running

from naoqi import ALProxy



class ALMecaLogger(object):
    def __init__(self):
        self.proxy = None

    def force_connect(self):
        self.proxy = ALProxy("ALMecaLogger")

    def ping(self):
        """Just a ping. Always returns true

        :returns bool: returns true
        """
        if not self.proxy:
            self.proxy = ALProxy("ALMecaLogger")
        return self.proxy.ping()

    def toDoWhenRobotHasFallen(self, arg1, arg2, arg3):
        """Increment the number of falls

        :param str arg1: arg
        :param AL::ALValue arg2: arg
        :param AL::ALValue arg3: arg
        """
        if not self.proxy:
            self.proxy = ALProxy("ALMecaLogger")
        return self.proxy.toDoWhenRobotHasFallen(arg1, arg2, arg3)

    def version(self):
        """Returns the version of the module.

        :returns str: A string containing the version of the module.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALMecaLogger")
        return self.proxy.version()

    def writeFiles(self):
        """Write results on disk
        """
        if not self.proxy:
            self.proxy = ALProxy("ALMecaLogger")
        return self.proxy.writeFiles()
