#!/usr/bin/env python
# Class autogenerated from /home/sam/Downloads/aldebaran_sw/nao/naoqi-sdk-2.1.4.13-linux64/include/alproxies/alpanoramacompassproxy.h
# by Sammy Pfeiffer's <Sammy.Pfeiffer at student.uts.edu.au> generator
# You need an ALBroker running

from naoqi import ALProxy


class ALPanoramaCompass(object):
    def __init__(self):
        self.proxy = ALProxy("ALPanoramaCompass")

    def getGenericProxy(self):
        """Gets the underlying generic proxy

        :returns boost::shared_ptr<ALProxy>: 
        """
        return self.proxy.getGenericProxy()

    def clearAllPanoramas(self, arg1):
        """

        :param bool arg1: arg
        :returns int: 
        """
        return self.proxy.clearAllPanoramas(arg1)

    def clearAllPanoramas2(self):
        """Delete all panorama files in the current working directory

        :returns int: 
        """
        return self.proxy.clearAllPanoramas()

    def clearPanorama(self, pIdentity):
        """Delete all files related to a given panorama in the current working directory

        :param int pIdentity: Panorama identity
        :returns int: 
        """
        return self.proxy.clearPanorama(pIdentity)

    def exit(self):
        """Exits and unregisters the module.
        """
        return self.proxy.exit()

    def getBrokerName(self):
        """Gets the name of the parent broker.

        :returns str: The name of the parent broker.
        """
        return self.proxy.getBrokerName()

    def getCurrentPanoramaDescriptor(self):
        """

        :returns AL::ALValue: Return an ALValue containing Panorama identity and contained Frames identity.
        """
        return self.proxy.getCurrentPanoramaDescriptor()

    def getCurrentPosition(self):
        """Return the current orientation of the robot in the current panorama.

        :returns AL::ALValue: 
        """
        return self.proxy.getCurrentPosition()

    def getFrame(self, id, arg2):
        """Return the Frame corresponding to the input identity. It have to be in the current Panorama

        :param int id: Identity of the resquested Frame.
        :param str arg2: arg
        :returns AL::ALValue: ALValue containing the Frame image part.
        """
        return self.proxy.getFrame(id, arg2)

    def getMethodHelp(self, methodName):
        """Retrieves a method's description.

        :param str methodName: The name of the method.
        :returns AL::ALValue: A structure containing the method's description.
        """
        return self.proxy.getMethodHelp(methodName)

    def getMethodList(self):
        """Retrieves the module's method list.

        :returns std::vector<std::string>: An array of method names.
        """
        return self.proxy.getMethodList()

    def getModuleHelp(self):
        """Retrieves the module's description.

        :returns AL::ALValue: A structure describing the module.
        """
        return self.proxy.getModuleHelp()

    def getUsage(self, name):
        """Gets the method usage string. This summarises how to use the method.

        :param str name: The name of the method.
        :returns str: A string that summarises the usage of the method.
        """
        return self.proxy.getUsage(name)

    def isDataAvailable(self):
        """Returns true if there is some panorama data

        :returns bool: 
        """
        return self.proxy.isDataAvailable()

    def isInPanorama(self):
        """Check if the robot is in the current Panorama.

        :returns int: Error status.
        """
        return self.proxy.isInPanorama()

    def isInPanorama2(self, arg1):
        """Check if the robot is in the current Panorama.

        :param int arg1: arg
        :returns int: Error status.
        """
        return self.proxy.isInPanorama(arg1)

    def isRelocalizationRequired(self):
        """Is a relocalization movement required.

        :returns bool: 
        """
        return self.proxy.isRelocalizationRequired()

    def isRunning(self, id):
        """Returns true if the method is currently running.

        :param int id: The ID of the method that was returned when calling the method using 'post'
        :returns bool: True if the method is currently running
        """
        return self.proxy.isRunning(id)

    def loadPanorama(self, id):
        """Load the panorama corresponding to the input identity from the hard drive. It has to exist.

        :param int id: Identity of the requested Panorama.
        :returns int: Error status.
        """
        return self.proxy.loadPanorama(id)

    def localize(self):
        """Localize the robot using the scan.

        :returns std::vector<float>: 
        """
        return self.proxy.localize()

    def localize2(self, pMode):
        """Localize the robot using the scan.

        :param bool pMode: Localization mode
        :returns std::vector<float>: 
        """
        return self.proxy.localize(pMode)

    def localize3(self, pMode):
        """Localize the robot using the scan.

        :param int pMode: Localization mode
        :returns std::vector<float>: 
        """
        return self.proxy.localize(pMode)

    def localize4(self, pMode, arg2):
        """Localize the robot using the scan.

        :param int pMode: Localization mode
        :param bool arg2: arg
        :returns std::vector<float>: 
        """
        return self.proxy.localize(pMode, arg2)

    def localizeNoHint(self):
        """Localize the robot using the scan,without hint.

        :returns std::vector<float>: 
        """
        return self.proxy.localizeNoHint()

    def pCall(self):
        """NAOqi1 pCall method.

        :returns AL::ALValue: 
        """
        return self.proxy.pCall()

    def ping(self):
        """Just a ping. Always returns true

        :returns bool: returns true
        """
        return self.proxy.ping()

    def setupPanorama(self):
        """Shoot a panorama at the current position.

        :returns int: 
        """
        return self.proxy.setupPanorama()

    def stop(self, id):
        """returns true if the method is currently running

        :param int id: the ID of the method to wait for
        """
        return self.proxy.stop(id)

    def version(self):
        """Returns the version of the module.

        :returns str: A string containing the version of the module.
        """
        return self.proxy.version()

    def wait(self, id, timeoutPeriod):
        """Wait for the end of a long running method that was called using 'post'

        :param int id: The ID of the method that was returned when calling the method using 'post'
        :param int timeoutPeriod: The timeout period in ms. To wait indefinately, use a timeoutPeriod of zero.
        :returns bool: True if the timeout period terminated. False if the method returned.
        """
        return self.proxy.wait(id, timeoutPeriod)
