#!/usr/bin/env python
# Class autogenerated from /home/sam/Downloads/aldebaran_sw/nao/naoqi-sdk-2.1.4.13-linux64/include/alproxies/alrobotpostureproxy.h
# by Sammy Pfeiffer's <Sammy.Pfeiffer at student.uts.edu.au> generator
# You need an ALBroker running

from naoqi import ALProxy


class ALRobotPosture(object):
    def __init__(self):
        self.proxy = ALProxy("ALRobotPosture")

    def getGenericProxy(self):
        """Gets the underlying generic proxy

        :returns boost::shared_ptr<ALProxy>: 
        """
        return self.proxy.getGenericProxy()

    def applyPosture(self, postureName, maxSpeedFraction):
        """Set the angle of the joints of the  robot to the choosen posture.

        :param str postureName: Name of the desired posture. Use getPostureList to get the list of posture name available.
        :param float maxSpeedFraction: A fraction.
        :returns bool: Returns if the posture was reached or not.
        """
        return self.proxy.applyPosture(postureName, maxSpeedFraction)

    def exit(self):
        """Exits and unregisters the module.
        """
        return self.proxy.exit()

    def getBrokerName(self):
        """Gets the name of the parent broker.

        :returns str: The name of the parent broker.
        """
        return self.proxy.getBrokerName()

    def getMethodHelp(self, methodName):
        """Retrieves a method's description.

        :param str methodName: The name of the method.
        :returns AL::ALValue: A structure containing the method's description.
        """
        return self.proxy.getMethodHelp(methodName)

    def getMethodList(self):
        """Retrieves the module's method list.

        :returns std::vector<std::string>: An array of method names.
        """
        return self.proxy.getMethodList()

    def getModuleHelp(self):
        """Retrieves the module's description.

        :returns AL::ALValue: A structure describing the module.
        """
        return self.proxy.getModuleHelp()

    def getPosture(self):
        """Determine posture.

        :returns str: 
        """
        return self.proxy.getPosture()

    def getPostureFamily(self):
        """Returns the posture family for example Standing, LyingBelly,...

        :returns str: Returns the posture family, e.g. Standing.
        """
        return self.proxy.getPostureFamily()

    def getPostureFamilyList(self):
        """Get the list of posture family names available.

        :returns std::vector<std::string>: 
        """
        return self.proxy.getPostureFamilyList()

    def getPostureList(self):
        """Get the list of posture names available.

        :returns std::vector<std::string>: 
        """
        return self.proxy.getPostureList()

    def getUsage(self, name):
        """Gets the method usage string. This summarises how to use the method.

        :param str name: The name of the method.
        :returns str: A string that summarises the usage of the method.
        """
        return self.proxy.getUsage(name)

    def goToPosture(self, postureName, maxSpeedFraction):
        """Make the robot go to the choosenposture.

        :param str postureName: Name of the desired posture. Use getPostureList to get the list of posture name available.
        :param float maxSpeedFraction: A fraction.
        :returns bool: Returns if the posture was reached or not.
        """
        return self.proxy.goToPosture(postureName, maxSpeedFraction)

    def isRunning(self, id):
        """Returns true if the method is currently running.

        :param int id: The ID of the method that was returned when calling the method using 'post'
        :returns bool: True if the method is currently running
        """
        return self.proxy.isRunning(id)

    def pCall(self):
        """NAOqi1 pCall method.

        :returns AL::ALValue: 
        """
        return self.proxy.pCall()

    def ping(self):
        """Just a ping. Always returns true

        :returns bool: returns true
        """
        return self.proxy.ping()

    def setMaxTryNumber(self, pMaxTryNumber):
        """Set maximum of tries ongoToPosture fail.

        :param int pMaxTryNumber: Number of retry if goToPosture fail.
        """
        return self.proxy.setMaxTryNumber(pMaxTryNumber)

    def stop(self, id):
        """returns true if the method is currently running

        :param int id: the ID of the method to wait for
        """
        return self.proxy.stop(id)

    def stopMove(self):
        """Stop the posture move.
        """
        return self.proxy.stopMove()

    def version(self):
        """Returns the version of the module.

        :returns str: A string containing the version of the module.
        """
        return self.proxy.version()

    def wait(self, id, timeoutPeriod):
        """Wait for the end of a long running method that was called using 'post'

        :param int id: The ID of the method that was returned when calling the method using 'post'
        :param int timeoutPeriod: The timeout period in ms. To wait indefinately, use a timeoutPeriod of zero.
        :returns bool: True if the timeout period terminated. False if the method returned.
        """
        return self.proxy.wait(id, timeoutPeriod)
