#!/usr/bin/env python
# Class autogenerated from /home/sam/Downloads/softbank/naoqi-sdk-2.5.5.5-linux64/include/alproxies/alrobotposeproxy.h
# by Sammy Pfeiffer's <Sammy.Pfeiffer at student.uts.edu.au> generator
# You need an ALBroker running

from naoqi import ALProxy



class ALRobotPose(object):
    def __init__(self):
        self.proxy = None

    def force_connect(self):
        self.proxy = ALProxy("ALRobotPose")

    def getActualPoseAndTime(self):
        """Get the actual robot pose and the time since this pose was activate.

        :returns AL::ALValue: A ALValue array of size 2. With first a string of the robot pose and  then a float with the time in second since this pose is activated.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALRobotPose")
        return self.proxy.getActualPoseAndTime()

    def getPoseNames(self):
        """Get the full list of pose possibly return by this module.

        :returns AL::ALValue: A ALValue array of string containing the possible Poses.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALRobotPose")
        return self.proxy.getPoseNames()

    def ping(self):
        """Just a ping. Always returns true

        :returns bool: returns true
        """
        if not self.proxy:
            self.proxy = ALProxy("ALRobotPose")
        return self.proxy.ping()

    def version(self):
        """Returns the version of the module.

        :returns str: A string containing the version of the module.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALRobotPose")
        return self.proxy.version()
