#!/usr/bin/env python
# Class autogenerated from /home/sam/Downloads/aldebaran_sw/nao/naoqi-sdk-2.1.4.13-linux64/include/alproxies/alservicemanagerproxy.h
# by Sammy Pfeiffer's <Sammy.Pfeiffer at student.uts.edu.au> generator
# You need an ALBroker running

from naoqi import ALProxy



class ALServiceManager(object):
    def __init__(self):
        self.proxy = None

    def force_connect(self):
        self.proxy = ALProxy("ALServiceManager")

    def isServiceRunning(self, name):
        """Tell if a service is running or not

        :param str name: Service's name
        :returns bool: 
        """
        if not self.proxy:
            self.proxy = ALProxy("ALServiceManager")
        return self.proxy.isServiceRunning(name)

    def ping(self):
        """Just a ping. Always returns true

        :returns bool: returns true
        """
        if not self.proxy:
            self.proxy = ALProxy("ALServiceManager")
        return self.proxy.ping()

    def restartService(self, name):
        """Restart a service of a package

        :param str name: Service's name
        :returns bool: 
        """
        if not self.proxy:
            self.proxy = ALProxy("ALServiceManager")
        return self.proxy.restartService(name)

    def serviceMemoryUsage(self, name):
        """Get the service's memory usage

        :param str name: Service's name
        :returns qi::uint32_t: 
        """
        if not self.proxy:
            self.proxy = ALProxy("ALServiceManager")
        return self.proxy.serviceMemoryUsage(name)

    def services(self):
        """Get all declared services

        :returns std::vector<AL::ALValue>: 
        """
        if not self.proxy:
            self.proxy = ALProxy("ALServiceManager")
        return self.proxy.services()

    def startService(self, name):
        """Start a service of a package

        :param str name: Service's name
        :returns bool: 
        """
        if not self.proxy:
            self.proxy = ALProxy("ALServiceManager")
        return self.proxy.startService(name)

    def stopService(self, name):
        """Stop a service of a package

        :param str name: Service's name
        :returns bool: 
        """
        if not self.proxy:
            self.proxy = ALProxy("ALServiceManager")
        return self.proxy.stopService(name)

    def version(self):
        """Returns the version of the module.

        :returns str: A string containing the version of the module.
        """
        if not self.proxy:
            self.proxy = ALProxy("ALServiceManager")
        return self.proxy.version()
